### PR TITLE
added individual label_dodge and push #41

### LINKED ISSUE #41: Function graph in README is broken
Graph of conversion functions is broken:

image

Most likely due to upstream changes in edge labeling in **ggraph** (?)

### PR DESCRIPTION
**Pull request by schochastics**
Seems like the `label_dodge` and `label_push` now require individual values for reciprocated ties.

### CODE REVIEW

**Comment by mbojan** [comment]
Cool! Is it some recent ggraph "upgrade"?

For some reason indentation in all the chunks changed. Would it be a problem to refrain from that?

**Comment by schochastics** [comment]
Yes there was a bigger update I think, but I was unaware of this change. Sorry for the indention, I fix that

**Comment by schochastics** [comment]
@mbojan this ok?

**Comment by mbojan** [comment]
That will do. Thanks!

**Pull request merged**
